/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const LocationRecommendation = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllLocationRecommendations' : IDL.Func(
      [],
      [IDL.Vec(LocationRecommendation)],
      ['query'],
    ),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getLocationRecommendations' : IDL.Func(
      [IDL.Text],
      [LocationRecommendation],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const LocationRecommendation = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllLocationRecommendations' : IDL.Func(
        [],
        [IDL.Vec(LocationRecommendation)],
        ['query'],
      ),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getLocationRecommendations' : IDL.Func(
        [IDL.Text],
        [LocationRecommendation],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };